# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
          day: 'tuesday'
          time: '08:00'
          timezone: 'Europe/Paris'
      commit-message:
          prefix: 'chore(deps)'
      open-pull-requests-limit: 30
      target-branch: main
      reviewers:
          - LoickBde
