version: '3'
services:
    postgre-db:
        image: postgres:latest
        container_name: money-tracker-db
        ports:
            - ${DB_PORT}:5432
        restart: always
        env_file:
            - postgre.env
        # volumes:
        # - ./init-money-tracker.sql:/docker-entrypoint-initdb.d/init.sql #to init db with init data
        # - ~/Developer/postgresql/money-tracker-db:/var/lib/postgresql/data # to create a volume
